M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Di 26 Mär 2024 21:28:38 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-26T21:28:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.500
%
G90
G05
T1
X146.722Y-51.565
X152.502Y-51.565
T2
X108.204Y-49.784
X150.622Y-106.426
X189.992Y-49.784
T0
M30
